<?php
//echo $this->exception;
//$oHeaderManager = Symbol_HeadManager::getInstance();
// Ajout du style de l'arborescence
//$oHeaderManager->linkFile('/backend/simple-lists.css');
//$oHeaderManager->linkFile('/backend/special-pages.css');
//$oHeaderManager->linkFile('/default/main/error.js');

$this->headScript()->appendFile(SCRIPTS_PATH . '/default/main/error.js');

$this->headLink()->appendStylesheet(STYLES_PATH . '/backend/simple-lists.css')
				 ->appendStylesheet(STYLES_PATH . '/backend/special-pages.css');

//ajout de la class dans le body définie par le template
$this->layout()->sBodyClass = "special-page error-bg red dark";

$aOption = array('title'=> $this->translate('Erreur'), 'description'=> $this->translate('error.description'), 'form'=> new Form_Error('10'));
$o = new Template_ErrorPage($aOption, $this->exception, APP_DEBUG);
echo $o->render();

	

