<?php
	/**	@brief Default Layout
	 * Chargement de la vue de l'application par défaut.
	 *
	 * @li Possibilité de charger le bas de la page, partie fixe "BOTTOM", à partir de la vue via la méthode @a placeholder()
	 * @code
	 * 	// Création d'un bouton
	 * 	$oButton = new Symbol_Button("fonction(js);", "Enregistrer");
	 *  // Enregistrement du contenu au format texte : ne pas oublier la méthode render() sur l'élément objet !
	 *  $this->placeholder("bottom")->set($oButton->render());
	 * @endcode
	 */



	// Initialisation de la balise Doctype.
	print $this->doctype();

	// On récupère l'éventuelle identité de la personne connectée.
	$oIdent = Zend_Auth::getInstance()->getIdentity();

	// Récupération de la langue en cours
	$local = Zend_Registry::get("Zend_Locale");

	// Création de la balise racine HTML.
	$oHtml = new Html_Symbol("html");
//	$oHtml->setAttributes(
//		array(
//			"xmlns"		=> "http://www.w3.org/1999/xhtml",
//			"xml:lang"	=> $local,
//			"lang"		=> $local
//		)
//	);

	/**
	 * Initialisation des balises d'entête reçu de la configuration
	 * principale dans le Bootstrap.
	 *
	 * @see application/Bootstrap.php->_initView()
	 */
	
	// Ajout du translate des éléments par défaut via la méthode "translate()" dans JavaScript
	$this->scriptTranslate("default");
	
	// Ajout du translate des éléments associés à la route via la méthode "translate()" dans JavaScript
	$this->scriptTranslate($this->aParams["route"]);
           
// 	// Chargement des éléments du HEADER
	
// 	if (($this->loading)) {
// 		// Fonctionnalité réalisée si une mise en attente de traitement est en cours
// 		$oMessageLoading = new Template_Message(Projet_DataHelper::translate($this->loading), true);
// 		$oMessageLoading->setStyleLoading();
// 		// Ajout du message dans l'article
// 		$oDivArticle->linkSymbol($oMessageLoading);
// 	}
// 	if (($this->info)) {
// 		// Fonctionnalité réalisée si un message est survenue
// 		$oMessageDefault = new Template_Message(Projet_DataHelper::translate($this->info), true);
// 		// Ajout du message dans l'article
// 		$oDivArticle->linkSymbol($oMessageDefault);
// 	}
	
