<?php
	// Initialisation de la balise Doctype.
	echo $this->doctype();
	$oHead = new Projet_Xml('head');
	$oHead->append(array($this->headLink(),
						 $this->jQuery(),
						 $this->headMeta(),
						 $this->headScript(),
						 $this->headStyle(),
						 $this->headTitle()
						));
	echo $oHead;
	// On récupère l'éventuelle identité de la personne connectée.
	$oIdent = Zend_Auth::getInstance()->getIdentity();

	// Récupération de la langue en cours
	//$local = Zend_Registry::get("Zend_Locale");

	// Ajout du translate des éléments par défaut via la méthode "translate()" dans JavaScript
	//$this->scriptTranslate("default");
	
	// Ajout du translate des éléments associés à la route via la méthode "translate()" dans JavaScript
	//$this->scriptTranslate($this->aParams["route"]);
           
// 	// Chargement des éléments du HEADER
	
// 	if (($this->loading)) {
// 		// Fonctionnalité réalisée si une mise en attente de traitement est en cours
// 		$oMessageLoading = new Template_Message(Projet_DataHelper::translate($this->loading), true);
// 		$oMessageLoading->setStyleLoading();
// 		// Ajout du message dans l'article
// 		$oDivArticle->linkSymbol($oMessageLoading);
// 	}
// 	if (($this->info)) {
// 		// Fonctionnalité réalisée si un message est survenue
// 		$oMessageDefault = new Template_Message(Projet_DataHelper::translate($this->info), true);
// 		// Ajout du message dans l'article
// 		$oDivArticle->linkSymbol($oMessageDefault);
// 	}

	$oBody = new Projet_Xml('body');
	

	//bare de coté pour les menus
	$oSideBar = new Projet_Xml('div');
	$oSideBar->setAttr('id', 'sidebar');
	//mise en place du logo
	$oLogo = new Projet_Xml('span');
	$oSideBar->append($oLogo);
	$oSideBar->append($this->navigation()->menu());
	
	$oBody->append($oSideBar);
	
	//zone pour l'identite du connecté
	$oLogin = new Projet_Xml('div');
	$oLogin->setAttr('id','zone-login');
	$oAncreLogin = new Projet_Xml('a',array('href' => '/fr/resume-connexion'));
	$oAncreLogin->append($this->loginZone($oIdent));
	$oLogin->append($oAncreLogin);
	
	$oBody->append($oLogin);
	
	//création d'un endroit pour le titre de la page courante
	$oTopTitre = new Projet_Xml('div');
	$oTopTitre->setAttr('id', 'TitreHaut');
	$oTitre = new Projet_Xml('h1');
	$oTitre->append($this->placeholder('TitreHaut'));
	$oTopTitre->append($oTitre);
	$oBody->append($oTopTitre);
	
	
	
	//creation de l'élément principal de contenu
	$oArticle = new Projet_Xml('div');
	$oArticle->setAttr('id', 'article');
	$oArticle->append($this->layout()->content);
	
	$oMessages = new Projet_Xml('div');
	$oMessages->setAttr('id', 'messages');
	$oMessages->append($this->parseMessages($this->messages));
	
	$oBody->append($oArticle);
	
	echo $oBody;
